GemeenteUtrecht/zaakafhandelcomponent

requirements/base.txt, requirements/ci.txt, requirements/dev.txt, src/zac/core/services.py, src/zac/core/tests/test_zaak_list.py
- filter server side
- removed client side check
- fixed bug leading to _all_ pages being consumed (ouch this hurts performance badly)
=> Optimized auth filters

package-lock.json, src/zac/advices/apps.py, src/zac/advices/forms.py, src/zac/advices/templates/advices/forms/widgets/doc_title.html, src/zac/core/cache.py, src/zac/core/camunda.py, src/zac/core/services.py, src/zac/core/templates/core/zaak_task.html, src/zac/core/tests/test_zaakafhandeling.py, src/zac/core/views/processes.py, src/zac/sass/components/_bag-object.scss, src/zac/sass/components/forms/_all.scss, src/zac/sass/components/forms/_formset.scss, src/zac/sass/components/tables/_table.scss, src/zac/sass/lib/_bem.scss
Fixes: https://github.com/GemeenteUtrecht/ZGW/issues/462
=> upload documents for advisors

src/zac/core/rollen.py, src/zac/core/services.py, src/zac/core/templates/core/zaak_detail.html, src/zac/core/tests/test_service.py
fixes https://github.com/GemeenteUtrecht/ZGW/issues/493
=> display BSN in Zaak detail page

src/zac/activities/models.py, src/zac/activities/query.py, src/zac/core/camunda.py, src/zac/core/services.py, src/zac/templates/index.html, src/zac/templates/master.html, src/zac/urls.py, src/zac/utils/decorators.py, src/zac/werkvoorraad/views.py
=> Werkvoorraad landing page

package-lock.json, src/zac/core/templates/core/zaak_detail.html
Added a lock button column to zaak-detail.page.
Fixes GemeenteUtrecht/ZGW#534
=> Added (un)locked button to documents on zaak-detail page

src/zac/core/api/permissions.py, src/zac/core/api/tests/test_add_document_permissions.py, src/zac/core/api/views.py, src/zac/core/permissions.py, src/zac/core/rules.py, src/zac/core/templates/core/zaak_detail.html, src/zac/js/views/zaak-detail/AddZaakDocument.js, src/zac/js/views/zaak-detail/index.js, src/zac/sass/components/forms/_all.scss, src/zac/sass/components/forms/_btn-row.scss, src/zac/tests/schemas/drc.yaml
* Adds permission to add documents (can be assigned via autorisatieprofielen)
* If permission is given, user sees a button to upload docs. API endpoint validates permissions.
=> Added button to add documents on zaak-detail page

src/zac/contrib/brp/tests/test_brp_api.py, src/zac/core/api/serializers.py, src/zac/core/api/tests/test_api_serializers.py, src/zac/core/api/utils.py, src/zac/core/api/views.py
=> Refactored NP extra info endpoint validation to serializer

package-lock.json, src/zac/contrib/brp/data.py, src/zac/contrib/brp/tests/test_brp_api.py, src/zac/core/api/serializers.py, src/zac/core/api/tests/test_api_serializers.py, src/zac/core/api/utils.py, src/zac/core/api/views.py
Even api aangepast zodat de gewilde data terugkomt. 
Expand query parameter toegevoegd.
=> Added expand parameter in query and serializer and changed return object

src/zac/contrib/kownsl/views.py, src/zac/notifications/tests/test_kownsl_review_submitted.py, src/zac/notifications/urls.py, src/zac/notifications/views.py, src/zac/tests/schemas/kownsl.yaml
This is the handler for the feature introduced in the latest Kownsl version: https://github.com/GemeenteUtrecht/kownsl/pull/19
=> Hook into Kownsl notifications

src/zac/notifications/subscriptions.py, src/zac/notifications/tests/test_subscribe_management_command.py, src/zac/tests/schemas/nrc.yaml
=> Rework declarations of desired subscriptions

README.md, backend/Dockerfile, backend/src/zac/conf/docker.py, backend/src/zac/conf/includes/base.py, backend/src/zac/conf/production.py, docker-compose.yml, frontend/zac-ui/Dockerfile-dev, ingress/Dockerfile, ingress/default.conf.template
=> Docker tweaks for the ZAC

.github/workflows/ci.yml, .github/workflows/code_quality.yml, backend/requirements/ci.txt, backend/requirements/dev.in, backend/requirements/dev.txt, backend/requirements/test-tools.in
=> Backend/SPA GitHub actions

backend/src/zac/core/forms.py, backend/src/zac/core/utils.py, docker-compose.yml
It works - but doesn't feel clean. @sergei-maertens ?
=> Added functionality to get path to UI for backend

backend/src/zac/conf/includes/base.py, backend/src/zac/core/api/bff_urls.py, backend/src/zac/core/api/serializers.py, backend/src/zac/core/api/tests/test_zaak_documents.py, backend/src/zac/core/api/tests/test_zaak_eigenschappen.py, backend/src/zac/core/api/tests/test_zaak_related_cases.py, backend/src/zac/core/api/tests/test_zaak_roles.py, backend/src/zac/core/api/views.py, backend/src/zac/core/views/utils.py, backend/src/zac/core/views/zaken.py, backend/src/zac/core/zaakobjecten.py, backend/src/zgw/models/zrc.py
=> Added more zaak-detail endpoints

backend/src/zac/core/api/bff_urls.py, backend/src/zac/core/api/filters.py, backend/src/zac/core/api/pagination.py, backend/src/zac/core/api/serializers.py, backend/src/zac/core/api/tests/test_eigenschappen.py, backend/src/zac/core/api/tests/test_zaaktypen.py, backend/src/zac/core/api/utils.py, backend/src/zac/core/api/views.py, backend/src/zac/utils/apps.py, backend/src/zac/utils/filters.py, backend/src/zac/utils/schema_extensions.py
=> add search endpoints

frontend/zac-ui/apps/zac-ui/src/app/kownsl/kownsl.component.html, frontend/zac-ui/libs/features/kownsl/src/lib/advice/advice.component.html, frontend/zac-ui/libs/features/kownsl/src/lib/advice/advice.component.ts, frontend/zac-ui/libs/features/kownsl/src/lib/approval/approval.component.html, frontend/zac-ui/libs/features/kownsl/src/lib/approval/approval.component.ts, frontend/zac-ui/libs/features/kownsl/src/lib/features-kownsl.component.html, frontend/zac-ui/libs/features/kownsl/src/lib/features-kownsl.component.ts, frontend/zac-ui/libs/features/kownsl/src/models/review-request.ts, frontend/zac-ui/libs/features/kownsl/src/models/zaak.ts, frontend/zac-ui/libs/shared/ui/components/src/lib/elements/loading-indicator/loading-indicator.component.scss
"Terug naar zaak" button in kownsl
=> Added returnUrl functionality

backend/src/zac/contrib/kownsl/api.py
Fixes https://github.com/GemeenteUtrecht/zaakafhandelcomponent/issues/175
=> Fixed get_review_request

backend/src/zac/api/polymorphism.py, backend/src/zac/camunda/api/serializers.py, backend/src/zac/camunda/apps.py, backend/src/zac/camunda/data.py, backend/src/zac/camunda/dynamic_forms/context.py, backend/src/zac/camunda/dynamic_forms/serializers.py, backend/src/zac/camunda/forms.py, backend/src/zac/camunda/tests/files/dynamic-form.bpmn, backend/src/zac/camunda/tests/files/no-form.bpmn, backend/src/zac/camunda/tests/test_dynamic_forms_task_context.py, backend/src/zac/camunda/user_tasks/context.py
Alternative implementation for #178
=> Dynamic forms task data context

frontend/zac-ui/libs/features/kownsl/src/lib/advice/advice.component.html, frontend/zac-ui/libs/features/kownsl/src/lib/advice/advice.component.ts, frontend/zac-ui/libs/features/kownsl/src/lib/approval/approval.component.html, frontend/zac-ui/libs/features/kownsl/src/lib/approval/approval.component.ts, frontend/zac-ui/libs/features/zaak-detail/src/lib/features-zaak-detail.component.html, frontend/zac-ui/libs/features/zaak-detail/src/lib/features-zaak-detail.component.ts, frontend/zac-ui/libs/features/zaak-detail/src/models/zaak.ts, frontend/zac-ui/libs/shared/ui/styling/src/lib/base/typography/_typography.scss, frontend/zac-ui/libs/shared/ui/styling/src/lib/elements/_elements.anchor.scss
=> Redirect to login button in kownsl and zaak-detail

backend/src/zac/accounts/api/permissions.py, backend/src/zac/accounts/api/serializers.py, backend/src/zac/accounts/api/tests/test_api_access_requests.py, backend/src/zac/accounts/api/urls.py, backend/src/zac/accounts/api/views.py, backend/src/zac/accounts/email.py, backend/src/zac/accounts/models.py, backend/src/zac/accounts/query.py, backend/src/zac/api/permissions.py, backend/src/zac/conf/includes/base.py, backend/src/zac/contrib/kownsl/tests/test_views.py, backend/src/zac/core/api/permissions.py, backend/src/zac/core/forms.py, backend/src/zac/core/rules.py, backend/src/zac/core/tests/test_zaak_detail.py, backend/src/zac/core/utils.py
=> create endpoint to grant zaak access

backend/requirements/base.txt, backend/requirements/ci.txt, backend/requirements/dev.txt, backend/src/zac/contrib/kownsl/api.py, backend/src/zac/contrib/kownsl/utils.py, backend/src/zac/contrib/kownsl/views.py, backend/src/zac/tests/schemas/kownsl.yaml
Relevant changes: https://github.com/GemeenteUtrecht/kownsl/pull/26
=> Handle pending Kownsl API schema changes

backend/src/zac/camunda/api/views.py
API docs look good now - @sergei-maertens ?
=> Added SubmitUserTaskSerializer to request body of schema

backend/src/zac/contrib/kownsl/tests/test_zaak_review_requests.py, backend/src/zac/core/api/tests/test_zaak_detail.py, backend/src/zac/core/api/tests/test_zaak_documents.py, backend/src/zac/core/api/tests/test_zaak_eigenschappen.py, backend/src/zac/core/api/tests/test_zaak_related_cases.py, backend/src/zac/core/api/tests/test_zaak_roles.py, backend/src/zac/core/api/tests/test_zaak_statuses.py, backend/src/zac/core/rules.py, backend/src/zac/core/tests/test_zaak_detail.py, backend/src/zac/core/tests/test_zaakafhandeling.py
=> access to zaak for connected users

backend/src/zac/activities/api/permissions.py, backend/src/zac/core/api/views.py
=> Fix reported 'activiteiten' bugs

backend/src/zac/core/api/serializers.py, backend/src/zac/core/api/tests/test_zaak_detail.py, backend/src/zac/core/api/views.py, backend/src/zac/elasticsearch/tests/test_api_zaken_search.py, backend/src/zac/werkvoorraad/tests/test_assignee_cases_endpoint.py
Related to https://github.com/GemeenteUtrecht/ZGW/issues/702
=> Added case result to zaakdetail api view

backend/requirements/base.in, backend/requirements/base.txt, backend/requirements/ci.txt, backend/requirements/dev.txt, backend/src/zac/contrib/dowc/api.py, backend/src/zac/contrib/dowc/tests/test_dowc_api.py, backend/src/zac/contrib/dowc/views.py
Related to: https://github.com/GemeenteUtrecht/dowc/pull/21.
=> Related to cleaning strategy of Do.W.C.

backend/src/zac/api/polymorphism.py, backend/src/zac/camunda/tests/test_user_task_view.py, backend/src/zac/contrib/dowc/fields.py, backend/src/zac/contrib/kownsl/camunda.py, backend/src/zac/contrib/validsign/tests/test_camunda.py, backend/src/zac/core/api/serializers.py, backend/src/zac/core/api/validators.py, backend/src/zac/core/api/views.py, backend/src/zac/core/camunda/select_documents/serializers.py, backend/src/zac/core/tests/test_select_documents.py
Dependent on https://github.com/GemeenteUtrecht/ZGW/pull/738
=> DocumentSelectTaskSerializer now includes document type

backend/requirements/base.txt, backend/requirements/ci.txt, backend/requirements/dev.txt, backend/src/zac/camunda/api/views.py, backend/src/zac/core/api/views.py
Includes a couple bugfixes, especially w/r to dynamic serializer
classes depending on the request method.
=> Bump to latest drf-spectacular

README.md
I thought that it could be helpful to add to the readme the steps that I took to start development on the frontend.
=> Added a few more info about getting started with Frontend

backend/src/zac/accounts/admin.py, backend/src/zac/accounts/models.py, backend/src/zac/accounts/templates/admin/accounts/widgets/checkbox_option_with_link.html, backend/src/zac/accounts/widgets.py, backend/src/zac/sass/admin/admin_overrides.scss, backend/src/zac/sass/admin/components/_all.scss, backend/src/zac/sass/admin/components/_checkbox-with-links.scss
issue - https://github.com/GemeenteUtrecht/ZGW/issues/773
As it was discussed with Jurjen and Sven first we will make some quick fix to make editing auth profiles easier
=> prettify select of blueprint permissions in the admin

backend/src/zac/camunda/api/serializers.py, backend/src/zac/camunda/data.py, backend/src/zac/camunda/tests/test_fetch_process_instances.py, backend/src/zac/camunda/tests/test_user_task_view.py, backend/src/zac/werkvoorraad/tests/test_user_tasks_endpoint.py
Reverts GemeenteUtrecht/zaakafhandelcomponent#341
=> Revert "Refs #337 -- correctly handle zac:doRedirect tasks"

backend/bin/docker_start.sh, docker-compose.yml, frontend/zac-ui/Dockerfile-dev, frontend/zac-ui/bin/docker_dev_start.sh, ingress/wait-for-services.sh
As discussed with minor changes to the docker_start file.
=> Fixes #820

backend/src/zac/elasticsearch/searches.py, backend/src/zac/elasticsearch/tests/test_search_and_order_zaken.py
fixes https://github.com/GemeenteUtrecht/ZGW/issues/777
=> search on a part of zaak.omschrijving

backend/doc/authorization.rst, backend/src/zac/accounts/permission_loaders.py, backend/src/zac/accounts/tests/test_command_add_atomic_permissions.py, backend/src/zac/activities/api/permission_loaders.py, backend/src/zac/activities/tests/test_grant_permissions_to_assignee.py
=> update atomic permission

backend/src/zac/api/polymorphism.py, backend/src/zac/core/api/bff_urls.py, backend/src/zac/core/api/filters.py, backend/src/zac/core/api/serializers.py, backend/src/zac/core/api/tests/test_zaak_eigenschappen_detail.py, backend/src/zac/core/api/views.py, backend/src/zac/core/services.py
issue - https://github.com/GemeenteUtrecht/ZGW/issues/608
=> edit case property

backend/src/zac/camunda/user_tasks/api.py, backend/src/zac/core/camunda/utils.py, backend/src/zac/werkvoorraad/api/urls.py, backend/src/zac/werkvoorraad/api/utils.py, backend/src/zac/werkvoorraad/api/views.py, backend/src/zac/werkvoorraad/tests/test_camunda_tasks_endpoint.py
Fixes: https://github.com/GemeenteUtrecht/ZGW/issues/855
=> Werkvoorraad "group" tasks

backend/src/zac/camunda/api/serializers.py, backend/src/zac/camunda/tests/test_user_task_view.py
Resolves https://github.com/GemeenteUtrecht/ZGW/issues/874
=> :bug: Fix empty form_key in user task bug

backend/src/zac/accounts/admin.py, backend/src/zac/accounts/api/viewsets.py, backend/src/zac/accounts/forms.py
Related to https://github.com/GemeenteUtrecht/ZGW/issues/912
=> :sparkles: Manage users in groups in django admin

backend/requirements/base.in, backend/requirements/base.txt, backend/requirements/ci.txt, backend/requirements/dev.txt, backend/src/zac/conf/dev.py, backend/src/zac/conf/includes/base.py, backend/src/zac/elasticsearch/management/commands/index_zaken.py
Depends on #416
---
```
(zac) ➜  backend git:(feature/index-zaken-progressbar) ✗ src/manage.py index_zaken --progress
Preloading all case types...
Fetched 91 case types
Starting zaken retrieval from the configured APIs
Number of cases in https://openzaak.utrechtproeftuin.nl/zaken/api/v1/:
6446
Now the real work starts, hold on!
Indexing   [##----------------------------------]    7%  00:07:38
```
=> index zaken progressbar

backend/src/zac/accounts/api/serializers.py, backend/src/zac/accounts/api/tests/test_authprofile.py, backend/src/zac/accounts/api/tests/test_permissions_delete.py
fixes https://github.com/GemeenteUtrecht/ZGW/issues/921
=> generate document blueprint permissions 

backend/requirements/base.in, backend/requirements/base.txt, backend/requirements/ci.txt, backend/requirements/dev.txt, backend/src/zac/conf/docker.py, backend/src/zac/conf/includes/base.py, backend/src/zac/conf/includes/environ.py, backend/src/zac/conf/includes/utils.py, backend/src/zac/conf/production.py
* performance logging disabled by default
* swap out deprecated raven for sentry-sdk
=> General project upgrades/improvements

backend/src/zac/contrib/dowc/permissions.py, backend/src/zac/contrib/dowc/views.py, backend/src/zac/core/api/permissions.py, backend/src/zac/core/api/tests/test_zaak_documents.py, backend/src/zac/core/api/views.py, backend/src/zac/core/views/utils.py
Fixes https://github.com/GemeenteUtrecht/ZGW/issues/1004
=> :bug: Fix document filtering process in list zaak documents

backend/doc/forms.rst
Fixes https://github.com/GemeenteUtrecht/ZGW/issues/965
=> :memo: Include zac:selectDocuments to forms.rst

backend/src/zac/core/camunda/select_documents/utils.py, backend/src/zac/core/tests/test_select_documents.py
Fixes https://github.com/GemeenteUtrecht/ZGW/issues/1026
=> :bug: Fix get_zaaktype_from_identificatie

backend/src/zac/elasticsearch/drf_api/serializers.py, backend/src/zac/elasticsearch/searches.py, backend/src/zac/elasticsearch/tests/test_api_zaken_search.py, backend/src/zac/elasticsearch/tests/test_search_and_order_zaken.py
Related to https://github.com/GemeenteUtrecht/ZGW/issues/981
=> :sparkles: Allow search on partial value of eigenschappen

frontend/zac-ui/libs/features/search/src/lib/search-form/object-search-form/zaak-object-search-form.component.ts, frontend/zac-ui/libs/features/zaak-detail/src/lib/documenten/document-toevoegen/document-toevoegen.component.ts, frontend/zac-ui/libs/features/zaak-detail/src/lib/documenten/document-vertrouwelijkheid-wijzigen/document-vertrouwelijkheid-wijzigen.component.ts, frontend/zac-ui/libs/features/zaak-detail/src/lib/documenten/documenten.service.ts
I was unable to validate this change because of potientially unrelated issues/configuration issues.
=> [NEEDS TESTING} Issue/#491

frontend/zac-ui/libs/features/zaak-detail/src/lib/keten-processen/configuration-components/adviseren-accorderen/adviseren-accorderen.component.ts
https://github.com/GemeenteUtrecht/ZGW/issues/1059
=> :bug: #1059 - Fout bij indienen advies/akkoord.

backend/src/zac/contrib/board/api/filters.py, backend/src/zac/contrib/board/api/serializer.py, backend/src/zac/contrib/board/tests/test_boarditem_api.py, frontend/zac-ui/libs/features/dashboard/src/lib/features-dashboard.component.html, frontend/zac-ui/libs/features/dashboard/src/lib/features-dashboard.component.ts, frontend/zac-ui/libs/features/dashboard/src/lib/features-dashboard.service.ts, frontend/zac-ui/libs/features/zaak-detail/src/lib/features-zaak-detail.component.html, frontend/zac-ui/libs/features/zaak-detail/src/lib/status/status.component.html, frontend/zac-ui/libs/features/zaak-detail/src/lib/status/status.component.ts, frontend/zac-ui/libs/features/zaak-detail/src/lib/status/status.service.ts, frontend/zac-ui/libs/shared/data-access/models/dashboard/board-item.ts, frontend/zac-ui/libs/shared/data-access/models/dashboard/dashboard.ts, frontend/zac-ui/libs/shared/data-access/models/index.ts, frontend/zac-ui/libs/shared/ui/components/src/lib/elements/multiselect/multiselect.component.html, frontend/zac-ui/libs/shared/ui/components/src/lib/elements/multiselect/multiselect.component.ts
issue - https://github.com/GemeenteUtrecht/ZGW/issues/1021 (backend part)
:boom: Breaking issue for BFF API
**Attention!** Don't merge until frontend is ready
=> dashboard api: zaak_url query param

backend/src/zac/activities/tests/factories.py
See https://github.com/GemeenteUtrecht/zaakafhandelcomponent/runs/4667886103?check_suite_focus=true
=> :bug: Add get_or_create to activityfactory to prevent db integrity error

backend/src/zac/core/services.py, backend/src/zac/notifications/tests/test_rol_created.py
Fixes https://github.com/GemeenteUtrecht/ZGW/issues/1122
=> :bug: #1122 - Reuse resolve_assignee to enrich role data

backend/src/zac/contrib/kownsl/tests/test_views.py, backend/src/zac/contrib/kownsl/views.py, frontend/zac-ui/libs/features/kownsl/src/lib/advice/advice.component.ts, frontend/zac-ui/libs/features/kownsl/src/lib/advice/advice.service.ts, frontend/zac-ui/libs/features/kownsl/src/lib/approval/approval.component.ts, frontend/zac-ui/libs/features/kownsl/src/lib/approval/approval.service.ts
Depends on:
https://github.com/GemeenteUtrecht/bptl/pull/170
https://github.com/GemeenteUtrecht/ZGW/pull/1169
=> :sparkles: Add task assignee to query param instead of taskid

backend/src/zac/core/api/filters.py, backend/src/zac/core/api/serializers.py, backend/src/zac/core/api/tests/test_eigenschappen.py, backend/src/zac/core/api/tests/test_zaak_eigenschappen_detail.py, backend/src/zac/core/api/utils.py, backend/src/zac/core/api/views.py, backend/src/zac/core/services.py, frontend/zac-ui/libs/features/search/src/lib/search-form/property-search-form/property-search-form.component.ts, frontend/zac-ui/libs/features/search/src/lib/search.service.ts, frontend/zac-ui/libs/features/search/src/models/zaaktype.ts, frontend/zac-ui/libs/features/zaak-detail/src/lib/features-zaak-detail.component.html, frontend/zac-ui/libs/features/zaak-detail/src/lib/informatie/informatie.component.html, frontend/zac-ui/libs/features/zaak-detail/src/lib/informatie/informatie.component.ts, frontend/zac-ui/libs/shared/data-access/models/zaken/zaak-eigenschap.ts, frontend/zac-ui/libs/shared/data-access/services/src/lib/zaak/zaak.service.ts
Related to https://github.com/GemeenteUtrecht/ZGW/issues/1155
=> #1155 Zaakinformatievelden

backend/src/zac/elasticsearch/api.py
Fixes https://github.com/GemeenteUtrecht/ZGW/issues/1225
=> :bug: Add zaak.omschrijving to update_zaak_document

backend/src/zac/camunda/api/data.py, backend/src/zac/camunda/api/serializers.py, backend/src/zac/camunda/api/urls.py, backend/src/zac/camunda/api/views.py, backend/src/zac/camunda/data.py, backend/src/zac/camunda/forms.py, backend/src/zac/camunda/processes.py, backend/src/zac/camunda/tests/files/harvo_behandelen.py, backend/src/zac/camunda/tests/test_fetch_process_instances.py, backend/src/zac/camunda/tests/test_user_task_history.py, backend/src/zac/camunda/tests/test_user_task_view.py, backend/src/zac/camunda/user_tasks/api.py, backend/src/zac/camunda/user_tasks/history.py, backend/src/zac/contrib/board/tests/test_boarditem_api.py, backend/src/zac/core/api/views.py, frontend/zac-ui/libs/features/zaak-detail/src/lib/features-zaak-detail.module.ts, frontend/zac-ui/libs/features/zaak-detail/src/lib/status/status.component.html, frontend/zac-ui/libs/features/zaak-detail/src/lib/task-history/historical-user-task-data.ts, frontend/zac-ui/libs/features/zaak-detail/src/lib/task-history/task-history.component.html, frontend/zac-ui/libs/features/zaak-detail/src/lib/task-history/task-history.component.ts, frontend/zac-ui/libs/features/zaak-detail/src/lib/task-history/task-history.service.ts, frontend/zac-ui/libs/shared/ui/components/src/lib/components/tabs/tab.component.scss
Resolves https://github.com/GemeenteUtrecht/ZGW/issues/1120
=> :sparkles: Retrieve camunda user task history for a zaak

backend/src/zac/core/api/serializers.py, backend/src/zac/core/api/tests/test_manage_zaak_document.py, frontend/zac-ui/libs/features/zaak-detail/src/lib/documenten/document-bestandsnaam-wijzigen/document-bestandsnaam-wijzigen.component.html, frontend/zac-ui/libs/features/zaak-detail/src/lib/documenten/document-bestandsnaam-wijzigen/document-bestandsnaam-wijzigen.component.spec.ts, frontend/zac-ui/libs/features/zaak-detail/src/lib/documenten/document-bestandsnaam-wijzigen/document-bestandsnaam-wijzigen.component.ts, frontend/zac-ui/libs/features/zaak-detail/src/lib/documenten/document-vertrouwelijkheid-wijzigen/document-vertrouwelijkheid-wijzigen.component.ts, frontend/zac-ui/libs/features/zaak-detail/src/lib/documenten/documenten.component.html, frontend/zac-ui/libs/features/zaak-detail/src/lib/documenten/documenten.component.ts, frontend/zac-ui/libs/features/zaak-detail/src/lib/documenten/documenten.module.ts, frontend/zac-ui/libs/features/zaak-detail/src/lib/documenten/documenten.service.ts, frontend/zac-ui/libs/shared/data-access/models/zaken/document.ts, frontend/zac-ui/libs/shared/ui/components/src/lib/components/form/form.component.html, frontend/zac-ui/libs/shared/ui/components/src/lib/components/form/form.component.ts
Resolves https://github.com/GemeenteUtrecht/ZGW/issues/1011
=> :sparkles: Allow changing of document bestandsnaam

backend/src/zac/accounts/tests/test_command_add_atomic_permissions.py, backend/src/zac/camunda/tests/test_user_task_view.py, backend/src/zac/contrib/kownsl/api.py, backend/src/zac/contrib/kownsl/camunda.py, backend/src/zac/contrib/kownsl/data.py, backend/src/zac/contrib/kownsl/serializers.py, backend/src/zac/contrib/kownsl/tests/test_camunda.py, backend/src/zac/contrib/kownsl/tests/test_convert_reviewrequest_to_json.py, backend/src/zac/contrib/kownsl/tests/test_kownsl_api.py, backend/src/zac/contrib/kownsl/tests/test_views.py, backend/src/zac/contrib/kownsl/tests/test_zaak_review_requests.py, backend/src/zac/notifications/tests/test_kownsl_review_submitted.py, backend/src/zac/tests/schemas/kownsl.yaml, frontend/zac-ui/libs/features/kownsl/src/lib/advice/advice.component.html, frontend/zac-ui/libs/features/kownsl/src/lib/approval/approval.component.html, frontend/zac-ui/libs/features/kownsl/src/models/review-request.ts
Depends on https://github.com/GemeenteUtrecht/kownsl/pull/39
=> :sparkles: Add more user details for review request requester

frontend/zac-ui/libs/features/zaak-detail/src/lib/documenten/document-toevoegen/document-toevoegen.component.ts, frontend/zac-ui/libs/features/zaak-detail/src/lib/documenten/documenten.service.ts, frontend/zac-ui/libs/features/zaak-detail/src/lib/informatie/informatie.component.ts, frontend/zac-ui/libs/shared/data-access/models/zaken/document.ts
https://github.com/GemeenteUtrecht/ZGW/issues/1376
https://github.com/GemeenteUtrecht/ZGW/issues/1219
=> Multiple issues

backend/src/zac/core/api/constants.py, backend/src/zac/core/api/serializers.py, backend/src/zac/core/api/tests/test_manage_zaak_document.py, backend/src/zac/core/api/validators.py
part of https://github.com/GemeenteUtrecht/ZGW/issues/1459
=> :passport_control: restrict filetypes and filenames on upload

backend/src/zac/accounts/api/tests/test_api_views.py, backend/src/zac/accounts/api/urls.py, backend/src/zac/accounts/api/views.py
part of [GemeenteUtrecht/ZGW/#1459](https://github.com/GemeenteUtrecht/ZGW/issues/1459)
=> :sparkles: Let a user log themselves out

frontend/zac-ui/libs/features/zaak-detail/src/lib/actions/activiteiten/activiteiten.component.html, frontend/zac-ui/libs/features/zaak-detail/src/lib/actions/checklist/checklist.component.html, frontend/zac-ui/libs/features/zaak-detail/src/lib/actions/checklist/checklist.component.ts, frontend/zac-ui/libs/features/zaak-detail/src/lib/actions/status/status.component.html, frontend/zac-ui/libs/features/zaak-detail/src/lib/actions/status/status.component.ts, frontend/zac-ui/libs/features/zaak-detail/src/lib/features-zaak-detail.component.html, frontend/zac-ui/libs/features/zaak-detail/src/lib/features-zaak-detail.component.ts, frontend/zac-ui/libs/features/zaak-detail/src/lib/overview/user-permissions/user-permissions.component.html, frontend/zac-ui/libs/features/zaak-detail/src/lib/overview/user-permissions/user-permissions.component.ts
Final layout as discussed with Vincent.
=> Restructure zaak detail

backend/src/zac/core/api/serializers.py, backend/src/zac/core/api/tests/test_zaak_roles.py, backend/src/zac/core/api/views.py
Related to https://github.com/GemeenteUtrecht/ZGW/issues/1385
=> :sparkles: Endpoint for destroying roles

backend/src/zac/core/camunda/start_process/data.py, backend/src/zac/core/camunda/start_process/tests/utils.py
Reverts GemeenteUtrecht/zaakafhandelcomponent#753
=> Revert ":bug: Fix BE FE build and start camunda process forms"

frontend/zac-ui/libs/features/zaak-detail/src/lib/gerelateerde-objecten/gerelateerde-objecten.component.html
=> :speech_balloon: #1723 - "Toevoegen --> Object toevoegen

backend/src/zac/conf/includes/base.py
Reverts GemeenteUtrecht/zaakafhandelcomponent#812
=> Revert ":mute: Remove template logs and fix typo in which package to log"

backend/src/zac/conf/includes/base.py
Reverts GemeenteUtrecht/zaakafhandelcomponent#809
=> Revert ":sparkles: Derive LOGGING settings from DEBUG by default and add ADFS …"

backend/src/zac/core/api/filters.py, backend/src/zac/core/api/tests/test_zaaktypen.py, frontend/zac-ui/libs/features/start-case/src/lib/features-start-case.component.ts, frontend/zac-ui/libs/shared/data-access/services/src/lib/meta/meta.service.ts
Fixes https://github.com/GemeenteUtrecht/ZGW/issues/1833
=> :sparkles: Only show active zaaktypen if requested

backend/doc/development/tezza/changelog.rst
Instead of https://github.com/GemeenteUtrecht/zaakafhandelcomponent/pull/864. Thanks @NumeGroenewegen.
=> :memo: Contezza release notes

backend/src/zac/camunda/tests/test_user_task_view.py, backend/src/zac/contrib/dowc/api.py, backend/src/zac/contrib/dowc/serializers.py, backend/src/zac/contrib/dowc/tests/test_dowc_api.py, backend/src/zac/contrib/dowc/views.py, backend/src/zac/core/camunda/zet_resultaat/context.py, backend/src/zac/core/camunda/zet_resultaat/serializers.py, backend/src/zac/core/tests/test_zet_resultaat.py, backend/src/zac/tests/schemas/dowc.yaml
Relies on https://github.com/GemeenteUtrecht/dowc/pull/52.
Related to https://github.com/GemeenteUtrecht/ZGW/pull/1934
Related to https://github.com/GemeenteUtrecht/ZGW/issues/1909
=> :sparkles: Warn if there are open documents for a zaak

backend/src/zac/contrib/objects/checklists/tests/test_checklist_response.py, backend/src/zac/contrib/objects/checklists/tests/test_grant_permissions_to_assignee.py, backend/src/zac/contrib/objects/services.py, backend/src/zac/core/api/serializers.py, backend/src/zac/core/api/tests/test_eigenschappen.py, backend/src/zac/core/api/tests/test_objects.py, backend/src/zac/core/api/tests/test_zaak_detail.py, backend/src/zac/core/api/tests/test_zaak_eigenschappen_detail.py, backend/src/zac/core/api/tests/test_zaak_related_objects.py, backend/src/zac/core/camunda/start_process/tests/test_get_start_process_context.py, backend/src/zac/core/camunda/start_process/tests/test_put_start_process_view.py, backend/src/zac/core/camunda/start_process/tests/test_start_camunda_zaak_process.py, backend/src/zac/core/services.py, backend/src/zac/elasticsearch/api.py, backend/src/zac/elasticsearch/documents.py, backend/src/zac/elasticsearch/drf_api/serializers.py, backend/src/zac/elasticsearch/management/commands/index_objecten.py, backend/src/zac/elasticsearch/tests/test_quick_search.py, backend/src/zac/notifications/tests/test_zaakobject_changed.py, backend/src/zac/notifications/tests/utils.py
Fixes backend for https://github.com/GemeenteUtrecht/ZGW/issues/1521
=> #1521 Add stringRepresentation to objects based on objecttypes label

backend/src/zac/contrib/dowc/views.py, backend/src/zac/core/cache.py, backend/src/zac/core/services.py, backend/src/zac/core/tests/test_cache_document.py, backend/src/zac/elasticsearch/api.py, backend/src/zac/notifications/handlers.py, backend/src/zac/notifications/tests/test_zaakinformatieobject_changed.py
Fixes https://github.com/GemeenteUtrecht/ZGW/issues/1982
=> :bug: Fix doc caching bug

backend/Dockerfile, backend/src/zac/conf/docker.py, backend/src/zac/conf/includes/base.py, backend/src/zac/urls.py
Reverts GemeenteUtrecht/zaakafhandelcomponent#948
=> Revert ":chart_with_upwards_trend: Switch debug_toolbar on for performance pr…"

backend/src/zac/accounts/api/fields.py, backend/src/zac/accounts/api/serializers.py, backend/src/zac/accounts/api/tests/test_group_viewsets.py, backend/src/zac/accounts/api/viewsets.py, backend/src/zac/activities/api/serializers.py, backend/src/zac/contrib/kownsl/camunda.py, backend/src/zac/contrib/kownsl/serializers.py, backend/src/zac/contrib/objects/checklists/api/serializers.py, backend/src/zac/core/api/fields.py, frontend/zac-ui/libs/features/auth-profiles/src/lib/user-groups/create-group/create-group.component.ts, frontend/zac-ui/libs/features/auth-profiles/src/lib/user-groups/user-groups.component.html, frontend/zac-ui/libs/shared/data-access/models/accounts/user-group.ts
Fixes BE for https://github.com/GemeenteUtrecht/ZGW/issues/2115
=> :sparkles: 2115 Fix user group bug

backend/src/zac/camunda/data.py, backend/src/zac/camunda/process_instances.py, backend/src/zac/camunda/tests/test_fetch_process_instances_view.py, backend/src/zac/camunda/tests/test_user_task_cancel.py, backend/src/zac/camunda/tests/test_user_task_history.py, backend/src/zac/camunda/user_tasks/api.py, backend/src/zac/camunda/user_tasks/history.py
Remove more inefficient camunda queries.
=> :racehorse::bug: Fix fetching camunda history

backend/src/zac/accounts/api/tests/test_management_api.py, backend/src/zac/accounts/api/urls.py, backend/src/zac/accounts/management/serializers.py, backend/src/zac/accounts/management/urls.py, backend/src/zac/accounts/management/views.py, backend/src/zac/camunda/api/views.py, backend/src/zac/contrib/objects/checklists/api/views.py, backend/src/zac/core/api/bff_urls.py, backend/src/zac/core/api/views.py, backend/src/zac/core/management/serializers.py, backend/src/zac/core/management/urls.py, backend/src/zac/core/management/views.py, backend/src/zac/core/tests/test_management_api.py, backend/src/zac/elasticsearch/drf_api/urls.py, backend/src/zac/elasticsearch/drf_api/views.py, backend/src/zac/elasticsearch/management/urls.py, backend/src/zac/elasticsearch/management/views.py, backend/src/zac/elasticsearch/tests/test_management_api.py
Resolves https://github.com/GemeenteUtrecht/ZGW/issues/2126
=> :sparkles: Add management endpoints

backend/src/zac/core/api/tests/test_betrokkene_identificatie.py, backend/src/zac/core/api/tests/test_manage_zaak_document.py, backend/src/zac/core/api/tests/test_vertrouwelijkheidsaanduidingen.py, backend/src/zac/core/api/views.py
Fixes: https://github.com/GemeenteUtrecht/ZGW/issues/2096
=> :sparkles: Add bestandsomvang to document upload to DRC

backend/src/zac/elasticsearch/documents.py, backend/src/zac/elasticsearch/searches.py, backend/src/zac/elasticsearch/tests/test_api_zaken_search.py
Fixes https://github.com/GemeenteUtrecht/ZGW/issues/2117
=> :sparkles: Update search on omschrijving config

backend/src/zac/core/api/serializers.py, backend/src/zac/core/api/tests/test_zaak_related_objects.py, backend/src/zac/core/api/views.py
Fixes https://github.com/GemeenteUtrecht/ZGW/issues/2046
=> :sparkles: ZAAKOBJECTen are unique

backend/requirements/base.in, backend/requirements/base.txt, backend/requirements/ci.txt, backend/requirements/dev.txt, backend/src/zac/contrib/dowc/tests/test_dowc_api.py, backend/src/zac/contrib/kownsl/tests/test_kownsl_api.py, backend/src/zac/contrib/kownsl/tests/test_review_request_views.py
Reverts GemeenteUtrecht/zaakafhandelcomponent#990
=> Revert ":arrow_up: Bump django-adfs in anticipation of migrating to mozilla-d…"

backend/src/zac/camunda/api/serializers.py, backend/src/zac/camunda/api/urls.py, backend/src/zac/camunda/api/views.py, backend/src/zac/camunda/tests/test_fetch_tasks_count_view.py, backend/src/zac/camunda/user_tasks/api.py
BE voor https://github.com/GemeenteUtrecht/ZGW/issues/2098
=> :sparkles: Add endpoint to count user tasks for user

backend/src/zac/camunda/api/views.py, backend/src/zac/camunda/tests/test_send_message.py
Fixes https://github.com/GemeenteUtrecht/ZGW/issues/2123
=> :sparkles: Set messageAssignee to request.user

backend/src/zac/core/api/serializers.py, backend/src/zac/core/api/tests/test_create_zaak.py
Related to https://github.com/GemeenteUtrecht/ZGW/issues/2110
=> :sparkles: Allow object URL to be sent with zaak creation request

backend/src/zac/core/camunda/select_documents/serializers.py
Fixes https://github.com/GemeenteUtrecht/ZGW/issues/2145
=> :bug: Add bestandsomvang in document selectie for bijdragezaak

backend/src/zac/accounts/management/commands/add_blueprint_permissions_for_zaaktypen.py
Fixes infrastructure to provide the right data efficiently for https://github.com/GemeenteUtrecht/ZGW/issues/2148
=> :bug: Fix bug in management endpoint for blueprint permissions

backend/src/zac/core/api/serializers.py, backend/src/zac/core/api/tests/test_create_zaak.py
Finalize https://github.com/GemeenteUtrecht/ZGW/issues/2110
=> :sparkles: Add objectUrl and objectType to create-zaak process

backend/src/zac/elasticsearch/api.py, backend/src/zac/elasticsearch/drf_api/serializers.py, backend/src/zac/elasticsearch/drf_api/views.py, backend/src/zac/elasticsearch/tests/test_api_zaken_search.py
Fixes https://github.com/GemeenteUtrecht/ZGW/issues/2081
=> :sparkles: Allows users to search on zaken by behandelaar or initiator

backend/src/zac/contrib/kownsl/api.py, backend/src/zac/contrib/objects/checklists/tests/test_unlock_checklists_management.py, backend/src/zac/elasticsearch/searches.py, backend/src/zac/tests/schemas/kownsl.yaml, backend/src/zac/werkvoorraad/serializers.py, backend/src/zac/werkvoorraad/tests/test_summary_endpoint.py, backend/src/zac/werkvoorraad/urls.py, backend/src/zac/werkvoorraad/utils.py, backend/src/zac/werkvoorraad/views.py
Depends on https://github.com/GemeenteUtrecht/kownsl/pull/61
Fixes https://github.com/GemeenteUtrecht/ZGW/issues/2174
=> #2174 - BE

backend/src/zac/core/api/serializers.py, backend/src/zac/core/api/tests/test_objects.py
Fixes https://github.com/GemeenteUtrecht/ZGW/issues/2186
=> :sparkles: Remove meta field in objecttypes properties

backend/src/zac/camunda/api/views.py, backend/src/zac/camunda/tests/test_fetch_tasks_count.py, backend/src/zac/camunda/user_tasks/api.py, backend/src/zac/contrib/dowc/serializers.py, backend/src/zac/contrib/dowc/tests/test_dowc_api.py, backend/src/zac/contrib/dowc/views.py, backend/src/zac/core/api/tests/test_objects.py, backend/src/zac/core/services.py, backend/src/zac/elasticsearch/api.py, backend/src/zac/werkvoorraad/tests/test_summary_endpoint.py, backend/src/zac/werkvoorraad/utils.py, backend/src/zac/werkvoorraad/views.py
Fixes https://github.com/GemeenteUtrecht/ZGW/issues/2215, https://github.com/GemeenteUtrecht/ZGW/issues/2265, https://github.com/GemeenteUtrecht/ZGW/issues/2255, https://github.com/GemeenteUtrecht/ZGW/issues/2254
=> :bug: Fix several smaller issues

backend/src/zac/conf/includes/base.py, backend/src/zac/core/api/bff_urls.py, backend/src/zac/core/api/tests/test_iots_view.py, backend/src/zac/core/api/views.py
Fixes https://github.com/GemeenteUtrecht/ZGW/issues/2304
=> :sparkles: Filter out importdocument IOT

backend/src/zac/core/api/tests/test_eigenschappen.py, backend/src/zac/core/api/utils.py, backend/src/zac/core/api/views.py, backend/src/zac/core/services.py, frontend/zac-ui/libs/features/zaak-detail/src/lib/overview/informatie/informatie.component.ts, frontend/zac-ui/libs/shared/ui/components/src/lib/components/form/field.ts, frontend/zac-ui/libs/shared/ui/components/src/lib/components/form/form.component.html, frontend/zac-ui/libs/shared/ui/components/src/lib/components/form/form.component.scss, frontend/zac-ui/libs/shared/ui/components/src/lib/elements/textarea/textarea.component.html, frontend/zac-ui/libs/shared/ui/components/src/lib/elements/textarea/textarea.component.ts, frontend/zac-ui/libs/shared/ui/styling/src/lib/base/typography/_typography.scss, frontend/zac-ui/libs/shared/ui/styling/src/lib/elements/_elements.textarea.scss
Fixes BE for https://github.com/GemeenteUtrecht/ZGW/issues/2308
=> :sparkles: Add long to tekst if length is more than 200

backend/src/zac/activities/tests/factories.py, backend/src/zac/camunda/tests/test_user_task_view.py, backend/src/zac/contrib/objects/services.py, backend/src/zac/core/camunda/zet_resultaat/context.py, backend/src/zac/core/camunda/zet_resultaat/serializers.py, backend/src/zac/werkvoorraad/views.py
Fixes https://github.com/GemeenteUtrecht/ZGW/issues/2295
=> 2 Feature/kill kownsl activities

backend/src/zac/camunda/dynamic_forms/serializers.py, backend/src/zac/camunda/dynamic_forms/tests/test_dynamic_form_validation.py, backend/src/zac/camunda/dynamic_forms/utils.py
Reverts GemeenteUtrecht/zaakafhandelcomponent#1206
=> Revert ":sparkles: Return spec to FE in dynamic camunda forms"

backend/src/zac/core/api/serializers.py, backend/src/zac/core/api/tests/test_zaak_detail.py
Should fix https://github.com/GemeenteUtrecht/ZGW/issues/2478
=> :bug: Fix faulty isConfigured: True when no processes exist

backend/src/zac/core/api/views.py, backend/src/zac/core/services.py
Reverts GemeenteUtrecht/zaakafhandelcomponent#1289
=> Revert ":sparkles: Add headers to open zaak calls"

.github/workflows/ci.yml, backend/Dockerfile, backend/src/zac/conf/docker.py
Reverts GemeenteUtrecht/zaakafhandelcomponent#1298
=> Revert ":loud_sound: Switch on debugging mode"
