GemeenteUtrecht/zaakafhandelcomponent

src/zac/core/forms.py

The BPTL task is deprecated, instead we pass along the kownsl-generated
frontend review URL into the subprocess.

Set kownsl frontend URL

---

requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/zac/core/services.py
src/zac/core/templates/core/zaak_besluiten.html
src/zac/core/templates/core/zaak_detail.html
src/zac/core/urls.py
src/zac/core/views/besluiten.py
src/zac/sass/components/_all.scss
src/zac/sass/components/_nav-menu.scss
src/zac/sass/components/_object-id-nav.scss

Besluit can be added through Open Zaak admin for now.
The table-display does not nearly convey all the available information - most notably the documents that hold the actual "besluit". Given the timeline, this did not make it into MVP.

Initial display of zaakbesluiten

---

src/zac/notifications/tests/test_zaak_destroyed.py
src/zac/notifications/views.py
src/zac/werkvoorraad/views.py

Conditions for crash:
- Ad-hoc activities assigned to logged in user
- one or more of the activities are for a zaak that cannot be retrieved from the API anymore

Fix crash on homepage when zaak no longer exists

---

src/zac/core/task_handlers.py
src/zac/core/views/processes.py

The URL to redirect to is stored in the session, which is read by the
PerformTaskView. If you execute a redirect-task, the URL is stored
in the session. When you then don't complete the task (yet), the value
is not cleared from the session. PerformTaskView is used for non-redirect
tasks as well, which then incorrectly receives information to redirect.
This patch removes the redirect-info if the form key does not match
the redirect-type of user task, preventing any windows from being opened
or being redirect to another page.

Fix session affecting other generic process forms

---

src/zac/accounts/templates/accounts/authorizationprofile_list.html

Displaying all the zaaktypen in the list-view leads to a cluttered
interface. This patch just summarizes the list to 'all zaaktypen are selected'.

De-clutter display of authorization profiles list

---

src/zac/accounts/templates/accounts/permissionset_form.html
src/zac/js/components/checkbox-select-dynamic/index.js

The bug was that a list of lists was passed to the `Set` constructor, rather than just the list of selected values to test.

Ensure that previously selected values are not reset

---

requirements/dev.in
requirements/dev.txt
src/zac/conf/dev.py
src/zac/core/services.py
src/zac/core/tests/test_zaak_list.py
src/zac/core/views/zaken.py
src/zac/elasticsearch/api.py
src/zac/elasticsearch/documents.py
src/zac/elasticsearch/searches.py
src/zac/elasticsearch/tests/utils.py

Related issue: https://github.com/GemeenteUtrecht/ZGW/issues/551
Changes:
* "Alle zaken" are queried using ES
* `get_zaken` function is refactored: query params from the filter form and filters based on permissions are separated. 
Todo (in the next PRs since we try to keep PRs small):
* use ES for querying zaken in the dashboard
* validate filter params before usin them in `get_zaken`, because it couldn't use some arbitrary parameters anymore

Initial experiment using ES index for permission-related list queries

---

src/zac/core/rollen.py
src/zac/core/services.py
src/zac/core/templates/core/zaak_detail.html

Fixes https://github.com/GemeenteUtrecht/ZGW/issues/597
The 'Rol' column in the Betrokkene table now shows the `roltype.omschrijving` instead of the `rol.omschrijving_generiek`.

Aanpassen weergave Betrokkene

---

src/zac/elasticsearch/documents.py
src/zac/elasticsearch/tests/test_index_zaken.py

This is a polymorphic resources, leading to errors when the first data seen is a date object,
but later data suddenly has another type (observed with empty string).

Don't create dynamic mappings for betrokkene_identificatie

---

src/zac/core/services.py

A Zaak must have an initial status, but because of bugs in the process
it can occur this is not the case. If the status is empty, we now return
None.

Slightly more robus handling of incomplete zaak-data

---

requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/zac/core/api/permissions.py
src/zac/core/api/serializers.py
src/zac/core/api/tests/test_add_zaak_relations.py
src/zac/core/api/urls.py
src/zac/core/api/views.py
src/zac/core/permissions.py
src/zac/core/rules.py
src/zac/core/templates/core/zaak_detail.html
src/zac/elasticsearch/searches.py
src/zac/elasticsearch/tests/utils.py
src/zac/js/constants.js
src/zac/js/views/zaak-detail/AddZaakRelation.js
src/zac/js/views/zaak-detail/index.js

Related ticket: #109 
An additional form in the zaak detail page was added. In this form, the related zaak and the type of relation can be filled out.

109 - Create Zaken relations from zaak-detail page

---

requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/zac/camunda/data.py
src/zac/camunda/history.py
src/zac/camunda/process_instances.py
src/zac/camunda/processes.py
src/zac/camunda/tests/test_fetch_process_instances.py
src/zac/core/camunda.py
src/zac/core/tests/test_claim_usertask.py
src/zac/core/tests/test_send_bpmn_message.py
src/zac/core/tests/test_submit_usertask.py
src/zac/core/views/processes.py

When Kownsl advices/approvals are recorded, notifications are sent and
handled by the ZAC. These handlers comlete the user task in the
Camunda process. Sometimes, these notifications can arrive before the
redirect is triggered, which also completes the user task.
The code is now adapted for this race condition where the notification
is handled before the redirect. In that case, the return URL validates
against the historic process instance/task, and if it's a historic
entry, it no longer attempts to complete the user task (since that
has been done already)

Fixing race condition bug on Kownsl approval/advice

---

backend/requirements/base.txt
backend/requirements/ci.txt
backend/requirements/dev.txt

`datum_tijd` was miss-autocompleted as `datum_type`, which lead to an error when using `datumTijd` eigenschap types.

Bump to bugfix release zgw-consumers

---

backend/src/zac/core/cache.py
backend/src/zac/core/services.py
backend/src/zac/notifications/handlers.py
backend/src/zac/notifications/subscriptions.py
backend/src/zac/notifications/tests/test_documenttype_created.py
backend/src/zac/notifications/tests/test_subscribe_management_command.py
backend/src/zac/notifications/tests/test_zaaktype_created.py
backend/src/zac/notifications/views.py

Fixes a `KeyError` when retrieving a zaak of a newly created zaaktype, while the cache of zaaktypen is still warm and doesn't include the new zaaktype yet.

Invalidate cache on mutation of zaaktype/informatieobjecttype

---

backend/src/zac/api/urls.py
backend/src/zac/camunda/api/serializers.py
backend/src/zac/camunda/api/views.py
backend/src/zac/camunda/tests/test_fetch_process_instances.py
backend/src/zac/camunda/urls.py
backend/src/zac/core/templates/core/zaak_detail.html
backend/src/zac/urls.py
frontend/zac-ui/libs/features/zaak-detail/src/lib/keten-processen/keten-processen.component.ts

Cleaned up URLs - moved from `/camunda/api/camunda/...` to `/api/camunda` so that all API urls are collected in the `zac.api` package. I've changed the URL in the frontend code for this as well.
Additionally, the possible error responses are now included, the correct success response schema and required input parameters.

Document internal Camunda process instances endpoint

---

.github/workflows/ci.yml
backend/src/zac/api/drf_spectacular/utils.py
backend/src/zac/api/urls.py
backend/src/zac/core/api/bff_urls.py
backend/src/zac/core/api/serializers.py
backend/src/zac/core/api/tests/test_add_document_permissions.py
backend/src/zac/core/api/tests/test_add_zaak_relations.py
backend/src/zac/core/api/urls.py
backend/src/zac/core/api/views.py
backend/src/zac/elasticsearch/drf_api/serializers.py
backend/src/zac/elasticsearch/drf_api/urls.py
backend/src/zac/elasticsearch/drf_api/views.py
backend/src/zac/js/components/documents/AddDocument.js
backend/src/zac/js/views/zaak-detail/AddZaakRelation.js

Added the following views to the API documentation
* list document types
* upload zaak-document
* create related zaak relation
* autocomplete search zaken based on identificatie
Additionally, included some more schema documentation for the search endpoints.
The schema tags are now set up so that:
* `search` groups endpoints dealing with search/autocomplete/...
* `meta` deals with catalogi API related endpoints (zaaktypen, eigenschappen, documenttypes)
* `core` deals with zaken/documenten (read & write)
@kelvincy be advised that some URLs have been refactored here:
- `/core/api/documents/upload` -> `/api/core/cases/document`
- `/core/api/documents/get-informatieobjecttypen` -> `/api/core/document-types`
- `/core/api/zaken_relation` -> `/api/core/cases/related-case`
- …

Ensure all used endpoints are documented

---

backend/src/zac/api/drf_spectacular/polymorphic.py
backend/src/zac/api/polymorphism.py
backend/src/zac/camunda/dynamic_forms/context.py
backend/src/zac/camunda/dynamic_forms/serializers.py
backend/src/zac/camunda/tests/test_dynamic_forms_task_context.py

* Implemented dynamic serializer by fetching the serializer fields from the task definition and calling that in the `__new__` method of the base serializer
* Fixed the schema generation to accommodate for arbitrary hash-maps (using `additionalProperties`), which is the case with this dynamic serializer.
I've considered creating a special base class for these HashMap-serializers, however the `drf_spectacular.openapi.resolve_serializer` will break on that because there are no `properties` in the schema, and it would be discarded (see issue https://github.com/tfranzel/drf-spectacular/issues/299).

Integrate dynamic forms

---

backend/src/zac/contrib/kownsl/data.py

Made some fields optional as the summary of the review request doesn't return all the previously mandatory fields.
Related to: https://github.com/GemeenteUtrecht/kownsl/pull/28

Make more fields optional in review request dataclass

---

backend/src/zac/contrib/kownsl/camunda.py
backend/src/zac/contrib/kownsl/tests/test_camunda.py

Fixes email part of: https://github.com/GemeenteUtrecht/ZGW/issues/701

Makes kownslFrontendUrl absolute so emails include the absolute url

---

backend/src/zac/core/api/serializers.py

After the update of the Object API, one path was no longer correct.

Fix API Schema

---

backend/src/zac/contrib/board/tests/test_boarditem_api.py
backend/src/zac/core/api/tests/test_add_zaak_relations.py
backend/src/zac/core/api/tests/test_zaak_detail.py
backend/src/zac/core/services.py
backend/src/zac/elasticsearch/api.py
backend/src/zac/elasticsearch/drf_api/views.py
backend/src/zac/elasticsearch/management/commands/index_zaken.py
backend/src/zac/elasticsearch/searches.py
backend/src/zac/elasticsearch/tests/test_api_zaken_search.py
backend/src/zac/elasticsearch/tests/test_index_zaken.py
backend/src/zac/elasticsearch/tests/utils.py
backend/src/zac/notifications/handlers.py
backend/src/zac/notifications/tests/test_rol_created.py
backend/src/zac/notifications/tests/test_status_created.py
backend/src/zac/notifications/tests/test_zaak_destroyed.py
backend/src/zac/notifications/tests/test_zaak_updated.py
backend/src/zac/notifications/tests/test_zaakeigenschap_changed.py
backend/src/zac/notifications/tests/utils.py
backend/src/zac/werkvoorraad/tests/test_assignee_cases_endpoint.py

Related to issue: #413.
I think the creation of elasticsearch documents should be separated from the saving and indexing of those documents. 
This is relevant for the bulk API of elasticsearch as well as making the code a little bit easier to handle (although more verbose). The creation and appending of inner docs is more explicit and the purpose of the related functions a bit more clear and aligned.
Performance changes (on local machine) based on ~6300 zaken with related objects.
- Baseline:
> - Time: ~3000 seconds
> - Peak memory usage of python process: ![baseline_index](https://user-images.githubusercontent.com/52245527/131112641-0c34a46d-083e-4749-891d-c561ea8aad4a.png)
- Bulk (without batch):
> - Time: ~700 seconds
> - Peak memory usage of python process: …

Increase index_zaken code coherence and performance

---

backend/src/zac/core/api/tests/test_zaak_documents.py
backend/src/zac/core/api/views.py

Before we allowed users to update the documents on the zaak detail page and the advice page, on top of the approval page, we wanted to prevent users from seeing documents that were still being approved and updated in approval processes (for example). 
Since allowing users to edit documents on the zaak detail as well as the advice page, this has become irrelevant and wrong document versions are now shown. This should fix that. 
I previously thought it was a cache problem, but I don't think it is as cache gets invalidated on a document level by the submission of the advice/approval and that's also how `get_documenten` is cached (on a per document basis rather than all documents together).
Fixes: https://github.com/GemeenteUtrecht/zaakafhandelcomponent/issues/411

:bug: Fix document versioning on zaak detail

---

backend/src/zac/core/api/bff_urls.py
backend/src/zac/core/api/filters.py
backend/src/zac/core/api/tests/test_zaak_related_objects.py
backend/src/zac/core/api/views.py
backend/src/zac/core/services.py

Issue - https://github.com/GemeenteUtrecht/ZGW/issues/900
I don't think that PATCH or PUT endpoint is needed here. Despite we now have PATCH support in Zaken API, it doesn't include object field, which can't be changed. So we can't change the object in the zaakobject. To do so you indeed need to delete the old object and to create the new one. It's the only way which is supported by Zaken API.

add DELETE endpoint for zaak objects

---

backend/src/zac/core/api/bff_urls.py
backend/src/zac/core/api/serializers.py
backend/src/zac/core/api/tests/test_manage_zaak_document.py
backend/src/zac/core/api/views.py

Issue #435  (backend)
---
**NOTE:**
The PR has a breaking change: 
* the path of the POST/PATCH endpoint `/api/core/cases/{bronorganisatie}/{identificatie}/document` is changed into `/api/core/cases/document` 
---

add url attribute to POST document endpoint

---

backend/src/zac/elasticsearch/management/commands/index_zaken.py

This seems to be the most straightforward method of keeping memory use stable and in check while still having better performance than original (~200% faster but also >200% slower than keeping max_workers at 10). 
I've scripted the indexing to be run with a range of max workers so you can see changes to the real and virtual memory and the total time until completion in each case.
You can easily see that there is no rampant increase in memory use throughout the entire indexing. Virtual memory increases the most. Using docker-compose and the following docker-compose.yml I'm actually unable to reproduce any OOM errors at all even though virtual memory is 0 in these cases.
```
version: '3.4'
services:
db:
image: postgres:11
environment:
- POSTGRES_USER=${DB_USER:-postgres}
- …
```

:sparkles: Add max_workers argument to index_zaken command

---

backend/src/zac/core/api/serializers.py
backend/src/zac/core/api/tests/test_zaak_detail.py
backend/src/zac/core/api/views.py

It's required now only when `vertrouwelijkheidaanduiding` is changed
Issue - GemeenteUtrecht/ZGW#941 (BE part)

Make 'reden' optional when patching zaak

---

frontend/zac-ui/libs/features/zaak-detail/src/lib/gerelateerde-objecten/gerelateerde-objecten.component.ts

Dit lost het probleem niet volledig op maar is ook een probleempje op zich. De rest van het problem is cache gerelateerd en het lijkt mij dat de backend moet wachten moet resolven totdat notificaties zijn afgehandeld/caches zijn geleegd?

:sparkles: #1317 - Fix incorrect callback when adding related object.

---

backend/src/zac/core/api/data.py
backend/src/zac/core/api/serializers.py
backend/src/zac/core/api/tests/test_manage_zaak_document.py
backend/src/zac/core/api/tests/test_zaak_documents.py
backend/src/zac/core/api/views.py
backend/src/zac/core/services.py

Takes the last edit from the audit trail of the document and includes it as lastEditedDate in the GET response.
Related to https://github.com/GemeenteUtrecht/ZGW/issues/1216

:sparkles: Add last_edited_date to list zaakdocument endpoint

---

frontend/zac-ui/libs/features/zaak-detail/src/lib/keten-processen/keten-processen.component.ts
frontend/zac-ui/libs/features/zaak-detail/src/lib/keten-processen/keten-processen.service.ts

Die `mergeTaskData`(line 146) functie was erg zwaar door array en string allocations en iterations. Deze functie werd bij elke poll om de 3s uitgevoerd. Ik heb de functie nu binnen een condition gezet omdat ie niet altijd uitgevoerd hoeft te worden. 
Line 148 - `this.updateProcessData(resData)` called ook die functie en heb ik ook binnen de condition geplaatst.
Daarnaast ook de poll naar 5s increased.

Improve ZAC performance

---

backend/src/zac/core/api/serializers.py
backend/src/zac/core/api/tests/test_zaak_eigenschappen.py
backend/src/zac/core/api/tests/test_zaak_eigenschappen_detail.py
backend/src/zac/core/api/views.py
backend/src/zac/core/services.py
frontend/zac-ui/libs/features/reports/src/lib/features-reports.component.ts
frontend/zac-ui/libs/features/zaak-detail/src/lib/informatie/informatie.component.ts
frontend/zac-ui/libs/shared/data-access/models/zaken/zaak-eigenschap.ts
frontend/zac-ui/libs/shared/data-access/services/src/lib/zaak/zaak.service.ts

Fix a bug where open-zaak does not support (partial) updates to zaakeigenschappen. Workflow is now from within the backend: create new zaakeigenschap with old zaakeigenschap specifications and eigenschap and delete the old zaakeigenschap. FE still does a patch request.
Also wherever `value` was used, now `waarde` is used. This is to align the language in the API and prevent English and Dutch from being mixed around.
Fixes https://github.com/GemeenteUtrecht/ZGW/issues/1440

:bug: Fix patching a zaakeigenschap

---

backend/src/zac/camunda/tests/test_user_task_view.py
backend/src/zac/core/camunda/zet_resultaat/context.py
backend/src/zac/core/tests/test_zet_resultaat.py
frontend/zac-ui/libs/features/zaak-detail/src/lib/actions/keten-processen/keten-processen.component.html
frontend/zac-ui/libs/features/zaak-detail/src/lib/actions/keten-processen/keten-processen.component.ts
frontend/zac-ui/libs/features/zaak-detail/src/lib/actions/keten-processen/keten-processen.service.ts

Related to https://github.com/GemeenteUtrecht/ZGW/issues/1704

:sparkles: Zaak annuleren now fetches choices from BPMN if configured

---

backend/src/zac/core/api/bff_urls.py
backend/src/zac/core/api/filters.py
backend/src/zac/core/api/tests/test_catalogi.py
backend/src/zac/core/api/tests/test_zaaktypen.py
backend/src/zac/core/api/views.py

Related to https://github.com/GemeenteUtrecht/ZGW/issues/1765
See http://localhost:8000/api/docs/#tag/meta/operation/core_catalogi_retrieve for list catalogus
See http://localhost:8000/api/docs/#tag/meta/operation/core_zaaktypen_list for domein filtering on zaaktype

:sparkles: Allow filtering zaaktypen on catalogus domein

---

backend/src/zac/contrib/objects/checklists/api/permissions.py
backend/src/zac/contrib/objects/checklists/api/serializers.py
backend/src/zac/contrib/objects/checklists/api/urls.py
backend/src/zac/contrib/objects/checklists/api/views.py
backend/src/zac/contrib/objects/checklists/data.py
backend/src/zac/contrib/objects/checklists/tests/test_checklist_permissions.py
backend/src/zac/contrib/objects/checklists/tests/test_checklist_response.py
backend/src/zac/contrib/objects/checklists/tests/test_grant_permissions_to_assignee.py
backend/src/zac/contrib/objects/checklists/tests/utils.py
backend/src/zac/contrib/objects/services.py
backend/src/zac/contrib/objects/tests/schemas/checklists_objects.yaml
frontend/zac-ui/libs/features/zaak-detail/src/lib/actions/checklist/checklist.component.html
frontend/zac-ui/libs/features/zaak-detail/src/lib/actions/checklist/checklist.component.ts
frontend/zac-ui/libs/features/zaak-detail/src/lib/actions/keten-processen/keten-processen.component.scss
frontend/zac-ui/libs/shared/data-access/services/src/lib/checklists/checklist.service.ts
frontend/zac-ui/libs/shared/ui/components/src/index.ts
frontend/zac-ui/libs/shared/ui/components/src/lib/components/form/form.component.ts

Fixes https://github.com/GemeenteUtrecht/ZGW/issues/2120
Camunda:
Zaak wordt aangemaakt in Camunda -> Checklist wordt ook in Camunda geinitialiseerd als er een checklisttype voor het zaaktype bestaat.
ZAC:
Een checklist bestaat al (dus hoeft niet gemaakt te worden).
Een bewerking vergt eerst POST naar https://zac.cg-intern..../checklist/bronorganisatie/zaakidentificatie/lock URL (geen data)
Daarna een PUT naar https://zac.cg-intern..../checklist/bronorganisatie/zaakidentificatie (met data)
In een succesvolle PUT wordt de checklist lockedBy ook gecleared.
Wat lukt niet:
Een PUT eerst en dan een lock request -> 403
Een lock op een al gelockte resource als jij niet de locker was -> 403
Een unlock als jij niet de locker was -> 403
Een PUT als jij niet de locker was -> 403

:sparkles: 2120 - checklist lock

---

backend/src/zac/camunda/tests/test_user_task_view.py
backend/src/zac/contrib/objects/kownsl/api/serializers.py
backend/src/zac/contrib/objects/kownsl/constants.py
backend/src/zac/contrib/objects/kownsl/data.py
backend/src/zac/contrib/objects/kownsl/tests/test_zaak_review_requests_views.py
backend/src/zac/core/camunda/zet_resultaat/serializers.py
backend/src/zac/core/tests/test_zet_resultaat.py
backend/src/zac/werkvoorraad/serializers.py

Fixes BE for https://github.com/GemeenteUtrecht/ZGW/issues/2162

3 :sparkles: Add status to summary review request view
